[package]
name = "rust-password-manager"
version = "0.1.0"
authors = ["NTaheij"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.114"
serde_json = "1.0.0"
magic-crypt = "3.1.3"
passwords = "3.1.2"